### ISSUE TITLE
Drop-In UI : Add an example to move `SpeedLimit` view to bottom left on top of `RoadNameLabel`

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android-examples#122]
Add an example to move `SpeedLimit` view to bottom left on top of `RoadNameLabel`. Changing the position of views is not allowed with Drop-In UI, but this can be achieved via a workaround using the following:
- Hide the `SpeedLimitView` by passing an empty binder
- Inject the default `MapboxSpeedLimitView` in `LeftFrameBinder` at bottom left.

Refs: https://github.com/mapbox/mapbox-navigation-android-examples/issues/132

**Comment by EricGeiler** [comment]
Here is our ideal layout for the bottom left...   pardon the crappy quality graphics.. I'm not a art major :)

![image](https://user-images.githubusercontent.com/61550186/185456678-3d3dd4a4-6b60-4816-8150-113c0cb1514c.png)

**Comment by abhishek1508** [comment]
Added a new example [here](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/app-preview/src/main/java/com/mapbox/navigation/examples/preview/dropinui/RepositionSpeedLimitActivity.kt)

cc @EricGeiler
