### ISSUE TITLE
Moving the speed limit position from top left to bottom left

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android-examples#132]
I am using Drop-In UI to write my navigation application. I want to position the speed limit view from top left to bottom left in NavigationView. The documentation says, position of views cannot be changed with Drop-In UI. However, this is something important for my application. Is there some workaround available?

**Comment by EricGeiler** [comment]
Here is a mock up what we'd like to see.

![image](https://user-images.githubusercontent.com/61550186/185456568-abf2bbfb-e692-454f-9545-3d79d252d7bb.png)

**Comment by abhishek1508** [comment]
Added a new example [here](https://github.com/mapbox/mapbox-navigation-android-examples/blob/main/app-preview/src/main/java/com/mapbox/navigation/examples/preview/dropinui/RepositionSpeedLimitActivity.kt)

cc @Sridhar261990
