### ISSUE TITLE
[Android Auto] Add favorites

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android-examples#28]
@kmadsen commented on [Thu May 27 2021](https://github.com/mapbox/1tap-android/issues/986)

The button is there, but it does nothing

<img width="385" alt="Screen Shot 2021-05-27 at 5 10 59 PM" src="https://user-images.githubusercontent.com/3021882/119911638-85319a80-bf0e-11eb-9f96-801d0f2ad0bd.png">

**Comment by kmadsen** [comment]
This has been added
