### ISSUE TITLE
Add more examples to the repo

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android-examples#51]
The issue lists all the examples that needs to be ported from `mapbox/mapbox-navigation-android` to be able to completely remove the examples module from the SDK public repo.

| examples(public SDK) | app(new repo) | status |
| --------- | ---- | ------- |
| MapboxCameraAnimationActivity | ShowCameraTransitionsActivity | ✅  |
| MapboxBuildingHighlightActivity | ShowBuildingExtrusionsActivity | ✅  |
| MapboxManeuverActivity | ShowManeuverActivity | ✅  |
| MapboxNavigationActivity | TurnByTurnExperienceActivity | ✅  |
| MapboxRouteLineAndArrowActivity | RenderRouteLineActivity | ✅  |
| MapboxTripProgressActivity | ShowTripProgressActivity | ✅  |
| MapboxVoiceActivity | PlayVoiceInstructionsActivity | ✅  |
| MultiLegRouteExampleActivity | ShowManeuverActivity | ✅  |
| MapboxMultipleArrowActivity | Not Applicable | ✅  |
| ReplayHistoryActivity | RouteReplayActivity | ✅  |
| MapboxJunctionsActivity | ShowJunctionsActivity | ✅ |
| MapboxSignboardActivity | ShowSignboardActivity | ✅ |
| Not Applicable | FetchARouteActivity | ✅  |
| Not Applicable | ShowCurrentLocationActivity | ✅  |
| Not Applicable | ShowSpeedLimitActivity | ✅  |
| MapboxCustomStyleActivity | Not Applicable | ✅  |
| IndependentRouteGenerationActivity | Not Applicable | ✅  |
| Not Applicable | ShowAlternativeRoutesActivity | ✅  |

/cc @zugaldia @truburt @LukasPaczos @Guardiola31337

**Comment by VysotskiVadim** [comment]
As we're working on examples, maybe it's also worth to add an example of alternatives? I remember a user who implemented switching between alternatives somehow wrong. But it was easy for him to reimplement when I shared a link to the [test app](https://github.com/mapbox/mapbox-navigation-android/blob/main/qa-test-app/src/main/java/com/mapbox/navigation/qa_test_app/view/AlternativeRouteActivity.kt#L361). @LukasPaczos , @dzinad, @truburt , @RingerJK , what do you think about it?
