### ISSUE TITLE
No cached version of com.mapbox.navigation:android:2.2.2 available for offline mode.

### ISSUE THREAD

**Issue by Lokarzz** [mapbox/mapbox-navigation-android-examples#76]
Got this error

No cached version of com.mapbox.navigation:android:2.2.2 available for offline mode.

Could not resolve com.mapbox.navigation:android:2.2.2.

How do we fix this? I just followed your installation guide in android

`https://docs.mapbox.com/android/navigation/guides/get-started/install/`

**Comment by LukasPaczos** [comment]
Hey @Lokarzz, this looks like a connection issue on your side. Are you still running into this problem?

**Comment by LukasPaczos** [comment]
Closing, feel free to open a new ticket if needed.
