### ISSUE TITLE
show user location not working on devices without google play services

### ISSUE THREAD

**Issue by raanaYavari** [mapbox/mapbox-navigation-android-examples#80]
Hello 
I have an issue with huawei devices and all devices without google play services
What should I do if I want to get user location from these devices?

**Comment by Guardiola31337** [comment]
cc'ing @mapbox/core-sdk to take a look as well, as this should be falling back to the built-in `LocationEngine` by default if Play Services are not available.

**Comment by VysotskiVadim** [comment]
@raanaYavari , thanks for reporting it 👍 

On which Android versions did you experience the issue? Currently there is [a known issue that location updates doesn't work on Android 12 without GP services](https://github.com/mapbox/mapbox-events-android/issues/564). Do you experience any location related issues on not Android 12 devices?

**Comment by VysotskiVadim** [comment]
I tested "Render current location on a map" example on different emulators without GP services. 
API 31 doesn't work, API 29 works.

**Comment by VysotskiVadim** [comment]
@raanaYavari , please reopen this issue if your case doesn't seem similar to https://github.com/mapbox/mapbox-events-android/issues/564. Otherwise feel free to continue discussion there.
