### ISSUE TITLE
Exclude Android auto Tags from Manifest. 

### ISSUE THREAD

**Issue by Mr-Ramzan** [mapbox/mapbox-navigation-android-examples#90]
I had recently added Mapbox sdk from official examples mainly the turn by turn, free drive module.
Upon submitting An update of old app I received a rejection regarding Android Auto.
I am looking for android auto support that I might have added in manifest but I could not find it. Can anyone please guide how to not add android auto sdk in my app.
Thank you

**Comment by abhishek1508** [comment]
Thank you for the question @Mr-Ramzan 

> I had recently added Mapbox sdk from official examples mainly the turn by turn, free drive module.

Can you please confirm if you referred to `app`, `app-preview` or `android-auto-app` module?

**Comment by Mr-Ramzan** [comment]
I had somehow added android auto dependency unknowingly. Sorry for inconvenience.
